import {getAppUser,uploadOwner} from '../../../auth';
import {token,digest,passwordHash,checkOrigin,clientIP} from '@/lib/auth-core.mjs';
import {db,bucket,run,rows,one,uid,now,auditLog} from '@/lib/onyx-db';
import {defaults,seed,kinds} from '@/lib/onyx-data';
import {bookingSchema,contactSchema,roles,states,permission,slotTimes,validDate} from '@/lib/onyx-validation';
import {z} from 'zod';
export const dynamic='force-dynamic';
export const runtime='nodejs';
class Failure extends Error{constructor(message:string,public status=400){super(message)}}
const response=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}});
async function member(){const u=await getAppUser();if(!u)throw new Failure('Sign in to continue.',401);const m=await one('SELECT id,email,name,role,artist,active,created FROM users WHERE email=? AND active=1',u.email.toLowerCase());if(!m)throw new Failure('Your account has not been granted studio access.',403);return {...m,identity:u.userId};}
async function allow(area:string,write=false){const m=await member();if(!permission(m.role,area,write))throw new Failure('Your role cannot perform this action.',403);return m;}
async function settings(){return {...defaults,...JSON.parse((await one('SELECT data FROM settings WHERE id=?','studio'))?.data||'{}')};}
async function rate(req:Request,action:string,max=10){const identity=(await getAppUser())?.userId||clientIP(req);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(identity)))).map(v=>v.toString(16).padStart(2,'0')).join('');const minute=Math.floor(Date.now()/3600000);const id=`${action}:${hash}:${minute}`;const entry=await run('INSERT INTO limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count',id,(minute+1)*3600000).first();if(entry.count>max)throw new Failure('Too many requests. Please try again later.',429);}
async function payload(req:Request):Promise<any>{if(Number(req.headers.get('content-length')||0)>100000)throw new Failure('Request too large.',413);return req.json();}
function parsed(r:any){return {...r,data:JSON.parse(r.data||'{}')};}
async function handle(req:Request){try{const url=new URL(req.url);const path=url.pathname.split('/api/onyx/')[1]?.split('/')||[];const [area,id]=path;const write=!['GET','HEAD'].includes(req.method);if(write){if(!checkOrigin(req))throw new Failure('Please reopen this form on the same site.',403);}
if(area==='bootstrap'){
 if(req.method==='GET'){const identity=await getAppUser();const count=await one('SELECT count(*) AS total FROM users');return response({identity:identity?{email:identity.email,name:identity.displayName}:null,setupRequired:count.total===0,member:identity?await one('SELECT id,email,name,role,artist FROM users WHERE email=? AND active=1',identity.email.toLowerCase()):null});}
 if(req.method==='POST')throw new Failure('The administrator is created automatically from your server environment. Sign in at /login.',410);
}
if(area==='public'&&req.method==='GET'){const records=(await rows("SELECT * FROM content WHERE status='published' ORDER BY sort,title")).map(parsed);const initialized=await one('SELECT id FROM settings WHERE id=?','initialized');return response({settings:await settings(),content:initialized?records:seed,demo:!initialized});}
if(area==='availability'&&req.method==='GET'){const date=url.searchParams.get('date')||'';const artist=url.searchParams.get('artist')||'';if(!validDate(date))throw new Failure('Choose a valid future date.');const s=await settings();const item=await one('SELECT * FROM content WHERE id=? AND kind=? AND status=?',artist,'artists','published');const a=item?parsed(item):seed.find(x=>x.id===artist);const data=a?.data||{};const day=new Date(date+'T12:00:00+05:30').getDay();const days=String(data.workingDays||'1,2,3,4,5,6').split(',').map(Number);const closed=String(s.holidays).split(',').map((v:string)=>v.trim()).includes(date)||String(data.holidays||'').split(',').includes(date)||!days.includes(day);const busy=await rows('SELECT time FROM slots WHERE artist=? AND date=?',artist,date);const times=Array.from({length:Math.max(0,(Number(data.endHour||s.endHour)-Number(data.startHour||s.startHour))*2)},(_,i)=>`${String(Number(data.startHour||s.startHour)+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`);return response({times:closed?[]:times.filter(t=>!busy.some(b=>b.time===t)),note:'Preferred times are subject to studio confirmation.'});}
if(area==='bookings'&&req.method==='POST'&&!id){await rate(req,'booking');const p=bookingSchema.parse(await payload(req));if(!validDate(p.date)||new Date(`${p.date}T${p.time}:00+05:30`).getTime()<Date.now())throw new Failure('Choose a future appointment time.');const initialized=await one('SELECT id FROM settings WHERE id=?','initialized');if(p.artist!=='any'){const a=initialized?await one("SELECT id FROM content WHERE id=? AND kind='artists' AND status='published'",p.artist):seed.find(x=>x.id===p.artist&&x.kind==='artists');if(!a)throw new Failure('Please choose an available artist.');}const user=await getAppUser();for(const ref of p.references){const file=await one('SELECT * FROM media WHERE id=? AND owner=? AND public=0',ref,await uploadOwner());if(!file)throw new Failure('A reference upload is unavailable. Please upload it again.');}const existing=await one('SELECT * FROM customers WHERE email=?',p.email);const customer=existing?.id||uid();const booking=`ONYX-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const data=JSON.stringify(p);const accessToken=token();const statements=[];if(!existing)statements.push(run('INSERT INTO customers (id,email,name,phone,marketing,created) VALUES (?,?,?,?,?,?)',customer,p.email,p.name,p.phone,p.marketing?1:0,now()));statements.push(run('INSERT INTO bookings (id,customer,artist,date,time,service,data,created) VALUES (?,?,?,?,?,?,?,?)',booking,customer,p.artist,p.date,p.time,p.service,data,now()),run('INSERT INTO notifications (id,title,booking,created) VALUES (?,?,?,?)',uid(),'New consultation request',booking,now()),auditLog(user?.userId||'visitor','BOOKING_REQUEST',booking,null,{date:p.date,artist:p.artist}));statements.push(run('INSERT INTO booking_access(token_hash,booking_id,created) VALUES (?,?,?)',digest(accessToken),booking,now()));await db().batch(statements);return response({id:booking,status:'PENDING',date:p.date,time:p.time,accessToken},201);}
if(area==='contact'&&req.method==='POST'){await rate(req,'contact');const p=contactSchema.parse(await payload(req));await run('INSERT INTO messages (id,name,email,category,message,created) VALUES (?,?,?,?,?,?)',uid(),p.name,p.email,p.category,p.message,now()).run();return response({ok:true},201);}
if(area==='event'&&req.method==='POST'){await rate(req,'events',200);const p=z.object({type:z.enum(['page_view','booking_start','booking_submit','booking_cta','whatsapp_click','portfolio_view']),path:z.string().max(200)}).parse(await payload(req));await run('INSERT INTO events (id,type,path,created) VALUES (?,?,?,?)',uid(),p.type,p.path,now()).run();return response({ok:true});}
if(area==='media'&&req.method==='POST'){await rate(req,'upload',30);if(Number(req.headers.get('content-length')||0)>9*1024*1024)throw new Failure('Upload is too large.',413);const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||file.size>8*1024*1024||file.size<8)throw new Failure('Choose a JPG, PNG or WebP image under 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const jpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const png=bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10';const webp=new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';const type=jpeg?'image/jpeg':png?'image/png':webp?'image/webp':'';if(!type||file.type!==type)throw new Failure('Image contents do not match the supported file type.');const publicFile=form.get('public')==='true';const u=await getAppUser();if(publicFile)await allow('media',true);const mediaId=uid();await bucket().put(mediaId,bytes,{httpMetadata:{contentType:type}});try{await run('INSERT INTO media (id,name,type,size,folder,owner,public,created) VALUES (?,?,?,?,?,?,?,?)',mediaId,file.name.replace(/[^a-zA-Z0-9._ -]/g,'').slice(0,150),type,file.size,String(form.get('folder')||'References').slice(0,50),await uploadOwner(),publicFile?1:0,now()).run();}catch(e){await bucket().delete(mediaId);throw e;}return response({id:mediaId,url:`/api/onyx/media/${mediaId}`},201);}
if(area==='media'&&id&&req.method==='GET'){const m=await one('SELECT * FROM media WHERE id=?',id);if(!m)throw new Failure('Image not found.',404);if(!m.public){const u=await getAppUser();if(await uploadOwner()!==m.owner){const staff=await member();const assigned=staff.role==='ARTIST'&&await one("SELECT b.id FROM bookings b, json_each(b.data,'$.references') r WHERE b.artist=? AND r.value=? LIMIT 1",staff.artist||'',id);if(!assigned&&!['SUPER_ADMIN','ADMIN','MANAGER','STAFF'].includes(staff.role))throw new Failure('Private reference.',403);}}const object=await bucket().get(id);if(!object)throw new Failure('Image not found.',404);return new Response(object.body,{headers:{'Content-Type':m.type,'Cache-Control':m.public?'public, max-age=86400':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'"}});}
if(area==='account'){const access=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';if(!access)throw new Failure('Enter your private booking access code.',401);const b=await one('SELECT b.* FROM booking_access a JOIN bookings b ON b.id=a.booking_id WHERE a.token_hash=?',digest(access));if(!b||id&&b.id!==id)throw new Failure('Booking access code is invalid.',403);if(req.method==='GET'){const {id,artist,date,time,duration,status,service,amount,paid,payment,created}=b;return response({bookings:[{id,artist,date,time,duration,status,service,amount,paid,payment,created,data:{description:parsed(b).data.description}}]});}if(req.method==='PATCH'&&id){const p=z.object({action:z.enum(['cancel','reschedule']),notes:z.string().max(2000)}).parse(await payload(req));await run('INSERT INTO notifications (id,title,booking,channel,data,created) VALUES (?,?,?,?,?,?)',uid(),p.action==='cancel'?'Customer requests cancellation':'Customer requests rescheduling',id,'admin',JSON.stringify({notes:p.notes}),now()).run();return response({ok:true});}}
if(area==='seed'&&req.method==='POST'){const m=await allow('settings',true);const current=await one('SELECT id FROM settings WHERE id=?','initialized');if(current)throw new Failure('Content has already been initialized.',409);await db().batch([...seed.map(i=>run('INSERT OR IGNORE INTO content (id,kind,slug,title,status,data,sort,updated) VALUES (?,?,?,?,?,?,?,?)',i.id,i.kind,i.slug,i.title,i.status,JSON.stringify(i.data),i.sort,now())),run('INSERT INTO settings (id,data) VALUES (?,?)','initialized','true'),auditLog(m.id,'INITIALIZE_DEMO','content')]);return response({ok:true});}
if(area==='dashboard'&&req.method==='GET'){const m=await member();const artist=m.role==='ARTIST';const bookings=await rows(`SELECT b.*,c.name,c.email,c.phone FROM bookings b JOIN customers c ON b.customer=c.id ${artist?'WHERE b.artist=?':''} ORDER BY b.date,b.time`,...(artist?[m.artist||'none']:[]));const notifications=artist?[]:await rows('SELECT * FROM notifications ORDER BY created DESC LIMIT 100');return response({member:m,artists:(await rows("SELECT * FROM content WHERE kind='artists' AND status='published'")).map(parsed),bookings:bookings.map(parsed),notifications,events:artist?[]:await rows('SELECT type,count(*) AS total FROM events GROUP BY type'),enquiries:artist?[]:await rows('SELECT * FROM messages ORDER BY created DESC'),customers:artist?[]:await rows('SELECT * FROM customers ORDER BY created DESC'),settings:await settings()});}
if(area==='content'){const m=await allow('content',write);if(req.method==='GET')return response({items:(await rows('SELECT * FROM content ORDER BY sort,title')).map(parsed)});if(req.method==='POST'||req.method==='PATCH'){const p=z.object({kind:z.enum(kinds as [string,...string[]]),slug:z.string().regex(/^[a-z0-9-]+$/).max(100),title:z.string().trim().min(1).max(200),status:z.enum(['draft','published','archived']),sort:z.number().int().min(0).max(10000),data:z.record(z.any())}).parse(await payload(req));if(JSON.stringify(p.data).length>50000)throw new Failure('Content is too long.');for(const key of ['image','beforeImage','video','instagram'])if(p.data[key]&&!/^(https:\/\/|\/(?!\/))/.test(p.data[key]))throw new Failure('Use an HTTPS URL or an uploaded image URL.');const itemId=id||uid();const before=id?await one('SELECT * FROM content WHERE id=?',id):null;await db().batch([run('INSERT INTO content (id,kind,slug,title,status,data,sort,updated) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,slug=excluded.slug,title=excluded.title,status=excluded.status,data=excluded.data,sort=excluded.sort,updated=excluded.updated',itemId,p.kind,p.slug,p.title,p.status,JSON.stringify(p.data),p.sort,now()),auditLog(m.id,id?'UPDATE':'CREATE',itemId,before,p)]);return response({ok:true,id:itemId});}if(req.method==='DELETE'&&id){const before=await one('SELECT * FROM content WHERE id=?',id);await db().batch([run('DELETE FROM content WHERE id=?',id),auditLog(m.id,'DELETE',id,before)]);return response({ok:true});}}
if(area==='bookings'&&id&&req.method==='PATCH'){const m=await allow('bookings',true);const before=await one('SELECT * FROM bookings WHERE id=?',id);if(!before)throw new Failure('Booking not found.',404);const p=z.object({artist:z.string().min(1),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time:z.string().regex(/^(1[01-9]):[03]0$/),duration:z.number().int().min(30).max(540).multipleOf(30),status:z.enum(states),notes:z.string().max(5000),amount:z.number().int().min(0).max(10000000),paid:z.number().int().min(0).max(10000000),payment:z.enum(['UNPAID','DEPOSIT','PAID','REFUNDED'])}).parse(await payload(req));if(p.paid>p.amount)throw new Failure('Paid amount cannot exceed the total.');const statements=[run('DELETE FROM slots WHERE booking=?',id)];if(['CONFIRMED','COMPLETED','NO-SHOW'].includes(p.status)){if(p.artist==='any')throw new Failure('Assign an artist before confirming.');const artist=await one("SELECT * FROM content WHERE id=? AND kind='artists' AND status='published'",p.artist);if(!artist)throw new Failure('Choose a published artist.');const a=parsed(artist).data;const s=await settings();const times=slotTimes(p.time,p.duration);if(p.status==='CONFIRMED'){if(!validDate(p.date)||new Date(`${p.date}T${p.time}:00+05:30`).getTime()<Date.now())throw new Failure('Choose a future time.');const day=new Date(p.date+'T12:00:00+05:30').getDay();if(!String(a.workingDays||'1,2,3,4,5,6').split(',').includes(String(day))||[...String(s.holidays).split(','),...String(a.holidays||'').split(',')].map(v=>v.trim()).includes(p.date))throw new Failure('The artist or studio is unavailable on this date.');if(Number(p.time.slice(0,2))<Number(a.startHour||s.startHour)||Number(times.at(-1)!.slice(0,2))>=Number(a.endHour||s.endHour))throw new Failure('The session extends beyond working hours.');}statements.push(...times.map(t=>run('INSERT INTO slots (id,booking,artist,date,time) VALUES (?,?,?,?,?)',uid(),id,p.artist,p.date,t)));}statements.push(run('UPDATE bookings SET artist=?,date=?,time=?,duration=?,status=?,notes=?,amount=?,paid=?,payment=? WHERE id=?',p.artist,p.date,p.time,p.duration,p.status,p.notes,p.amount,p.paid,p.payment,id),auditLog(m.id,'UPDATE_BOOKING',id,before,p));if(before.status!==p.status||before.date!==p.date||before.time!==p.time)statements.push(run('INSERT INTO notifications (id,title,booking,channel,status,data,created) VALUES (?,?,?,?,?,?,?)',uid(),`Booking ${p.status.toLowerCase()}`,id,'email','not_configured',JSON.stringify({date:p.date,time:p.time}),now()));await db().batch(statements);return response({ok:true});}
if(area==='settings'){const m=await allow('settings',write);if(req.method==='GET')return response({settings:await settings()});if(req.method==='POST'){const p=z.object({name:z.string().min(1).max(100),address:z.string().max(400),phone:z.string().max(30),email:z.union([z.string().email(),z.literal('')]),whatsapp:z.string().regex(/^\d{7,15}$|^$/),instagram:z.union([z.string().url(),z.literal('')]),hours:z.string().max(100),hero:z.string().max(100),intro:z.string().max(200),about:z.string().max(5000),timezone:z.literal('Asia/Kolkata'),currency:z.literal('INR'),startHour:z.number().min(10).max(19),endHour:z.number().min(11).max(20),minimum:z.number().min(0),hourly:z.number().min(0),deposit:z.number().min(0),tax:z.number().min(0).max(100),holidays:z.string().max(3000),themeSwitch:z.boolean()}).parse(await payload(req));if(p.startHour>=p.endHour)throw new Failure('Closing time must follow opening time.');if(p.instagram&&!p.instagram.startsWith('https://'))throw new Failure('Use an HTTPS social URL.');const before=await settings();await db().batch([run('INSERT INTO settings (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data','studio',JSON.stringify(p)),auditLog(m.id,'UPDATE_SETTINGS','studio',before,p)]);return response({ok:true});}}
if(area==='users'){const m=await allow('users',write);if(req.method==='GET')return response({items:await rows('SELECT id,email,name,role,artist,active,created FROM users ORDER BY created')});if(req.method==='POST'){const p=z.object({email:z.string().email().transform(v=>v.toLowerCase()),name:z.string().min(1).max(100),role:z.enum(roles),artist:z.string().nullable().optional(),active:z.number().int().min(0).max(1),password:z.string().min(12).max(128).optional()}).parse(await payload(req));if(p.email===m.email&&(p.role!=='SUPER_ADMIN'||p.active!==1))throw new Failure('You cannot remove your own administrator access.');const u=await one('SELECT id,email,name,role,artist,active,created FROM users WHERE email=?',p.email);if(!u&&!p.password)throw new Failure('Set an initial password of at least 12 characters.');const hash=p.password?await passwordHash(p.password):null;const {password,...safe}=p;const userId=u?.id||uid();const ops=[run('INSERT INTO users (id,email,name,role,artist,active,created,password_hash) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role,artist=excluded.artist,active=excluded.active,password_hash=COALESCE(excluded.password_hash,users.password_hash)',userId,p.email,p.name,p.role,p.artist||null,p.active,now(),hash),auditLog(m.id,'UPSERT_USER',p.email,u,safe)];if(hash||p.active===0)ops.push(run('DELETE FROM auth_sessions WHERE user_id=?',userId));await db().batch(ops);return response({ok:true});}}
if(area==='media'&&!id&&req.method==='GET'){await allow('media');return response({items:await rows('SELECT * FROM media WHERE public=1 ORDER BY created DESC')});}
if(area==='media'&&id&&req.method==='DELETE'){const m=await allow('media',true);const record=await one('SELECT * FROM media WHERE id=? AND public=1',id);if(!record)throw new Failure('Media not found.',404);if(await one('SELECT id FROM content WHERE data LIKE ?',`%${id}%`))throw new Failure('This image is used by content. Replace it there first.');await bucket().delete(id);await db().batch([run('DELETE FROM media WHERE id=?',id),auditLog(m.id,'DELETE_MEDIA',id,record)]);return response({ok:true});}
if(area==='audit'&&req.method==='GET'){await allow('content');return response({items:await rows('SELECT * FROM audit ORDER BY created DESC LIMIT 500')});}
if(area==='notifications'&&id&&req.method==='PATCH'){await allow('notifications',true);await run("UPDATE notifications SET status='read' WHERE id=? AND channel='admin'",id).run();return response({ok:true});}
if(area==='enquiries'&&id&&req.method==='PATCH'){await allow('enquiries',true);const p=z.object({status:z.enum(['unread','read','resolved'])}).parse(await payload(req));await run('UPDATE messages SET status=? WHERE id=?',p.status,id).run();return response({ok:true});}
if(area==='customers'&&id&&req.method==='PATCH'){const m=await allow('customers',true);const p=z.object({notes:z.string().max(5000)}).parse(await payload(req));await db().batch([run('UPDATE customers SET notes=? WHERE id=?',p.notes,id),auditLog(m.id,'UPDATE_CUSTOMER',id,null,p)]);return response({ok:true});}
throw new Failure('This action is unavailable.',404);
}catch(e){if(e instanceof z.ZodError)return response({error:e.issues[0]?.message||'Check the form values.'},400);if(e instanceof Failure)return response({error:e.message},e.status);const message=String(e);if(message.includes('UNIQUE constraint'))return response({error:message.includes('slots')?'This artist already has a session at that time. Choose another slot.':'That record already exists. Refresh and try again.'},409);console.error('ONYX request failed',e);return response({error:'The studio service is temporarily unavailable. Your form has not been cleared; please try again.'},503);}}
export const GET=handle;export const POST=handle;export const PATCH=handle;export const DELETE=handle;
