import {z} from 'zod';
export const roles=['SUPER_ADMIN','ADMIN','MANAGER','ARTIST','STAFF','VIEWER'] as const;
export const states=['PENDING','CONFIRMED','RESCHEDULE REQUESTED','COMPLETED','CANCELLED','NO-SHOW'] as const;
const short=z.string().trim().max(300);
export const bookingSchema=z.object({name:short.min(2),email:z.string().email().max(200).transform(v=>v.toLowerCase()),phone:z.string().trim().regex(/^[+\d\s()-]{7,20}$/,'Enter a valid phone number'),whatsapp:short.optional().default(''),service:short.min(1),style:short.min(1),artist:short.min(1),placement:short.min(1),size:short.min(1),description:z.string().trim().min(10,'Describe your idea in at least 10 characters').max(5000),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time:z.string().regex(/^(1[01-9]):[03]0$/),budget:short,colour:short,notes:z.string().max(3000).default(''),references:z.array(z.string().uuid()).max(3).default([]),age:z.literal(true,{errorMap:()=>({message:'Confirm you are at least 18'})}),consent:z.literal(true,{errorMap:()=>({message:'Consent is required'})}),marketing:z.boolean().default(false),source:short.default('website')});
export const contactSchema=z.object({name:short.min(2),email:z.string().email().max(200),category:short.min(1),message:z.string().trim().min(10).max(5000),consent:z.literal(true)});
export function slotTimes(time:string,duration:number){const [h,m]=time.split(':').map(Number);return Array.from({length:Math.ceil(duration/30)},(_,i)=>{const t=h*60+m+i*30;return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;});}
export function validDate(date:string){const d=new Date(date+'T00:00:00+05:30');return !Number.isNaN(d.getTime())&&new Date(d.getTime()+19800000).toISOString().slice(0,10)===date&&date>=new Date(Date.now()+19800000).toISOString().slice(0,10)&&d.getTime()<Date.now()+366*86400000;}
export function permission(role:string,area:string,write=false){if(role==='SUPER_ADMIN')return true;if(['users','settings'].includes(area))return false;if(role==='ADMIN')return true;if(['bookings','customers','calendar','enquiries','notifications'].includes(area))return ['MANAGER','STAFF'].includes(role)||(!write&&['ARTIST','VIEWER'].includes(role));return !write&&role==='VIEWER';}
