export type Item={id:string;kind:string;slug:string;title:string;status:string;sort:number;data:Record<string,any>;updated?:string};
export const styles=['Realism','Black & Grey','Fine Line','Minimal','Traditional','Neo Traditional','Portrait','Geometric','Mandala','Lettering','Colour','Custom','Cover-up'];
export const kinds=['artists','portfolio','styles','services','testimonials','gallery','blog','offers','faqs','aftercare','pages','flash'];
export const defaults={name:'ONYX Tattoo Studio',address:'Near Mr. DIY, Shreenagar Extension, Khajrana Road, Jhad Colony, Indore – 452018',phone:'',email:'',whatsapp:'',instagram:'',hours:'By appointment',hero:'YOUR SKIN.\nOUR CANVAS.',intro:'Some stories deserve more than words.',about:'A personal idea. An original design. A mark that stays with you. ONYX brings art and identity together in Indore.',timezone:'Asia/Kolkata',currency:'INR',startHour:11,endHour:20,minimum:0,hourly:0,deposit:0,tax:0,holidays:'',themeSwitch:true};
const item=(kind:string,slug:string,title:string,data:Record<string,any>,sort=0):Item=>({id:`${kind}-${slug}`,kind,slug,title,status:'published',sort,data});
export const seed:Item[]=[
item('artists','artist-one','Artist One',{subtitle:'BLACK & GREY · REALISM',description:'Demonstration artist profile. Replace with the studio artist’s biography, experience and verified work before launch.',image:'/images/artist.webp',specialties:'Black & Grey, Realism',experience:'Demo profile',demo:true,workingDays:'1,2,3,4,5,6',startHour:11,endHour:20}),
item('artists','artist-two','Artist Two',{subtitle:'FINE LINE · MINIMAL',description:'Demonstration artist profile. A space for the artist’s individual approach and story.',image:'/images/work.webp',specialties:'Fine Line, Minimal',experience:'Demo profile',demo:true,workingDays:'1,2,3,4,5,6',startHour:11,endHour:20},1),
item('artists','artist-three','Artist Three',{subtitle:'TRADITIONAL · CUSTOM',description:'Demonstration artist profile. Replace with verified studio content.',image:'/images/sleeve.webp',specialties:'Traditional, Custom',experience:'Demo profile',demo:true,workingDays:'1,2,3,4,5,6',startHour:11,endHour:20},2),
item('portfolio','stories-in-shade','Stories in shade',{style:'Black & Grey',artist:'artists-artist-one',image:'/images/sleeve.webp',description:'An exploration of contrast, texture and the human canvas. Illustrative photography; not claimed as ONYX work.',placement:'Arm',size:'Custom',duration:'Discuss at consultation',demo:true},0),
item('portfolio','under-the-surface','Under the surface',{style:'Realism',artist:'artists-artist-one',image:'/images/work.webp',description:'A closer look at the craft. Illustrative photography, not an ONYX commission.',placement:'Arm',size:'Custom',duration:'Discuss at consultation',demo:true},1),
item('portfolio','a-mark-of-your-own','A mark of your own',{style:'Custom',artist:'artists-artist-three',image:'/images/detail.webp',description:'Ideas take shape through considered placement and careful detail. Illustrative photography.',placement:'Forearm',size:'Custom',duration:'Discuss at consultation',demo:true},2),
...styles.map((s,i)=>item('styles',s.toLowerCase().replaceAll(' & ','-').replaceAll(' ','-'),s,{description:`Explore ${s.toLowerCase()} with an artist. Bring your references and we will discuss a direction that suits your idea, placement and scale.`},i)),
...['Custom Tattoo','Consultation','Cover-up','Piercing','Touch-up'].map((s,i)=>item('services',s.toLowerCase().replaceAll(' ','-'),s,{description:['Built around your story, drawn for your skin. Start with a conversation and develop an original piece with your artist.','Explore your ideas, placement and references. Your artist will discuss the design, timing and a personal quote.','A fresh direction for an existing tattoo. An in-person assessment helps establish what can be achieved.','Discuss placement, jewellery and availability directly with the studio.','Ask the studio to assess your healed tattoo and advise on the next step.'][i]},i)),
...[
['first-tattoo','Your first tattoo, thoughtfully planned.','Bring a few references, but also bring your own story. Think about placement, scale and how the piece will work with your day-to-day life. A consultation gives you space to ask questions and understand the process.'],
['choosing-placement','A place for your story.','Placement changes how a design moves and how often you see it. Discuss visibility, scale and the natural shape of the area with your artist. Try the stencil before making your final decision.'],
['custom-design','From an idea to something yours.','A useful reference communicates mood, composition or a detail you love. Your artist can use that starting point to develop original work, rather than copy another person’s tattoo.']
].map(([slug,title,description],i)=>item('blog',slug,title,{description,image:['/images/work.webp','/images/sleeve.webp','/images/detail.webp'][i],category:'Studio notes',demo:true},i)),
...[
['How do I book?','Send a consultation request with your idea, preferred artist and date. The studio reviews the request before confirming an appointment.'],
['What will my tattoo cost?','Every design is different. Size, detail, placement and time all contribute. The studio confirms a quote after consultation; submitting a request does not charge you.'],
['Can I bring a reference?','Yes. Upload up to three reference images with your request. They help communicate your idea; your final design should be original.'],
['Can you cover an existing tattoo?','Send a clear photo and request a cover-up consultation. An artist needs to assess the existing work before advising on a design.'],
['Can I choose my artist?','Yes. Select an artist in the booking form, or choose “Help me choose” and let the studio match your idea.'],
['Is my request a confirmed appointment?','No. A request is pending until the studio confirms the artist, time and scope.']
].map(([title,description],i)=>item('faqs',`question-${i+1}`,title,{description},i)),
...[
['about','A studio for stories.','ONYX is a space for personal expression through tattoo art. Based in Indore, the experience begins with a conversation about what you want to carry with you.'],
['studio','Step into ONYX.','Visit the studio near Mr. DIY on Khajrana Road, Indore. Please request an appointment before your visit so the team can make time for your consultation.'],
['hygiene','Care is part of the craft.','Ask your artist to explain their equipment, single-use supplies, workstation preparation and aftercare process before your session. Detailed studio protocols will be published after confirmation by ONYX.'],
['aftercare','The art continues after you leave.','Follow the written, individual aftercare instructions provided by your artist. Care depends on your dressing, skin and procedure. Ask a qualified healthcare professional about any concerning symptoms.'],
['privacy','Your information, handled with care.','Booking information and reference images are collected to respond to your request and manage appointments. Reference images are private. Marketing consent is optional. Contact the studio to request access, correction or deletion. Draft policy: the studio must confirm its contact details, retention period and legal terms before accepting real customer data.'],
['terms','A clear understanding.','Submitting a booking request does not guarantee an appointment or a price. Design, timing, eligibility and payment terms are confirmed during consultation. Draft terms require studio review before public launch.'],
['cancellation','Plans can change.','Contact the studio as early as possible if you need to change your appointment. Deposit and cancellation terms must be confirmed before payment. Draft policy awaiting the studio’s approved notice period and refund rules.']
].map(([slug,title,description])=>item('pages',slug,title,{description})),
];
export const publicRoutes=['','about','artists','portfolio','styles','services','pricing','booking','studio','hygiene','aftercare','testimonials','faqs','journal','gallery','offers','contact','privacy','terms','cancellation','flash','custom'];
