import {z} from 'zod';
import {one,run,db,uid,now,auditLog} from '@/lib/onyx-db';
import {passwordMatches,passwordHash,digest,checkOrigin,clientIP,safeReturn} from '@/lib/auth-core.mjs';
import {beginSession,endSession,getAppUser} from '@/app/auth';
export const runtime='nodejs';
export const dynamic='force-dynamic';
function reply(data:any,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
async function limit(id:string,max:number){const hour=Math.floor(Date.now()/3600000);const r=await run('INSERT INTO limits(id,count,expires) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count','auth:'+digest(id)+':'+hour,(hour+1)*3600000).first();return r.count<=max;}
export async function POST(req:Request){if(!checkOrigin(req))return reply({error:'Open this form using the configured website address.'},403);try{if(Number(req.headers.get('content-length')||0)>5000)return reply({error:'Request too large'},413);const raw=await req.text();if(raw.length>5000)return reply({error:'Request too large'},413);const data=JSON.parse(raw);const action=new URL(req.url).pathname.split('/').at(-1);if(action==='login'){const p=z.object({email:z.string().email().max(200).transform(v=>v.toLowerCase().trim()),password:z.string().min(1).max(128),returnTo:z.string().max(300).optional()}).parse(data);if(!await limit('ip:'+clientIP(req),100)||!await limit('email:'+p.email,15))return reply({error:'Too many sign-in attempts. Please try again in an hour.'},429);const u=await one('SELECT * FROM users WHERE email=? AND active=1',p.email);if(!await passwordMatches(p.password,u?.password_hash))return reply({error:'Email or password is incorrect.'},401);await beginSession(u.id);await auditLog(u.id,'LOGIN','session').run();return reply({ok:true,returnTo:safeReturn(p.returnTo)});}if(action==='logout'){const u=await getAppUser();await endSession();if(u)await auditLog(u.userId,'LOGOUT','session').run();return reply({ok:true});}if(action==='password'){const u=await getAppUser();if(!u)return reply({error:'Sign in to change your password.'},401);if(!await limit('password:'+u.userId,10))return reply({error:'Too many attempts. Try again later.'},429);const p=z.object({current:z.string().max(128),password:z.string().min(12).max(128)}).parse(data);const record=await one('SELECT password_hash FROM users WHERE id=?',u.userId);if(!await passwordMatches(p.current,record.password_hash))return reply({error:'Current password is incorrect.'},400);const hash=await passwordHash(p.password);await db().batch([run('UPDATE users SET password_hash=? WHERE id=?',hash,u.userId),run('DELETE FROM auth_sessions WHERE user_id=?',u.userId),auditLog(u.userId,'CHANGE_PASSWORD','account')]);await beginSession(u.userId);return reply({ok:true});}return reply({error:'Not found'},404);}catch(e){if(e instanceof z.ZodError)return reply({error:e.issues[0]?.message||'Check your input.'},400);if(e instanceof SyntaxError)return reply({error:'Invalid JSON.'},400);console.error('Authentication operation failed');return reply({error:'Sign-in is temporarily unavailable. Please try again.'},503);}}
